# Generated by Django 6.0.3 on 2026-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature_2m', models.FloatField(help_text='°C')),
                ('relative_humidity_2m', models.FloatField(help_text='%')),
                ('apparent_temperature', models.FloatField(help_text='°C, feels-like')),
                ('wind_speed_10m', models.FloatField(help_text='km/h')),
                ('wind_direction_10m', models.FloatField(help_text='degrees')),
                ('weather_code', models.IntegerField(help_text='WMO weather interpretation code')),
                ('is_day', models.BooleanField(default=True)),
                ('sunrise', models.DateTimeField(blank=True, null=True)),
                ('sunset', models.DateTimeField(blank=True, null=True)),
                ('moonrise', models.DateTimeField(blank=True, null=True)),
                ('moonset', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
