# Generated by Django 6.1 on 2026-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('us_aqi', models.IntegerField(help_text='US Air Quality Index (0-500)')),
                ('pm2_5', models.FloatField(help_text='PM2.5 concentration, µg/m³')),
                ('pm10', models.FloatField(help_text='PM10 concentration, µg/m³')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
