# Generated by Django 6.1 on 2026-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_airqualityrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('recorded_at', models.DateTimeField(help_text='The actual historical timestamp this data represents')),
                ('temperature_2m', models.FloatField()),
                ('relative_humidity_2m', models.FloatField()),
                ('apparent_temperature', models.FloatField()),
                ('wind_speed_10m', models.FloatField()),
                ('wind_direction_10m', models.FloatField()),
                ('weather_code', models.IntegerField()),
                ('precipitation', models.FloatField(help_text='mm, actual recorded precipitation')),
                ('pressure_msl', models.FloatField(help_text='hPa, mean sea level pressure')),
                ('cloud_cover', models.FloatField(help_text='%')),
            ],
            options={
                'ordering': ['city_name', 'recorded_at'],
                'indexes': [models.Index(fields=['city_name', 'recorded_at'], name='weather_his_city_na_3c8afd_idx')],
            },
        ),
    ]
