# Generated by Django 5.2 on 2026-09-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_historicalweatherrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='moon_phase',
            field=models.FloatField(blank=True, help_text='Moon phase (0-27.99)', null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalweatherrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
